### ISSUE TITLE
Support for union + nested hierarchies?

### ISSUE THREAD

**Issue by krishpop** [brentyi/dcargs#6]
I have an experiment with two types of models that can run, each with its own configs. In my ExperimentConfig, I have a `model_class` parameter which is of type `Union[ModelAConfig, ModelBConfig]`, and defaults to `ModelAConfig`. When I call dcargs.cli(ExperimentConfig), how do I set which config to use, as well as the respective parameters in it?

In general, how can Union over two types of configs be used if each config has its own set of parameters?

Edit: Closing this, I think this is addressed with using [multiple subparsers](https://brentyi.github.io/dcargs/examples/10_multiple_subparsers/)

**Comment by brentyi** [comment]
Glad you got it figured out!!

As an FYI subcommands will get much more configurable once #5 is merged.
