### ISSUE TITLE
Generic dataclass detection fails for unions

### ISSUE THREAD

**Issue by pculbertson** [brentyi/dcargs#7]
Hi Brent,

I have a very low-level bug to flag for you -- when saving/loading nested dataclasses to yaml (using `extras.to_yaml()`, `extras.from_yaml()`, if a dataclass has a Union of two custom types, they don't get detected as custom types for the `yaml.Loader` to construct.

I wrote a MWE to replicate the issue:
```
import dataclasses
import dcargs

from typing import Union

@dataclasses.dataclass
class TypeA:
    data: int

@dataclasses.dataclass
class TypeB:
    data: int
    
@dataclasses.dataclass
class Wrapper:
    subclass: Union[TypeA, TypeB] = TypeA(1)
    
if __name__ == "__main__":
    wrapper1 = Wrapper() # Create Wrapper object.
    wrapper2 = dcargs.extras.from_yaml(Wrapper, dcargs.extras.to_yaml(wrapper1)) # Errors, no constructor for TypeA
```

No worries if this is too low-level to deal with right now -- I think we can work around it by just pickling the configs, but wanted to flag something is going awry in the custom type detection.

**Comment by pculbertson** [comment]
Wow thanks so much for the lightning-quick patch :)

**Comment by brentyi** [comment]
oops, seems it was too fast and the CI is broken :) 

looking into it...

**Comment by brentyi** [comment]
Actually, everything seems to be in order; just had a typo in a test + an outdated version of `typing_extensions` locally.

Appreciate the issue report + reproduction instructions! As an FYI I am thinking of deprecating the API though, I can think of a couple other issues and the benefit over just using PyYAML seems fairly incremental. Will file a separate issue.

**Comment by pculbertson** [comment]
Thanks, appreciate the heads-up! I wanted to file an issue in case the `Union` typing issue went further than just the YAML utils. Before your patch, we were just pickling the dataclass objects with no problem, we might just stick with that.

**Comment by brentyi** [comment]
Sounds good!

If you haven't considered it, I'd recommend also looking into serializing with PyYAML + the standard `yaml.load(your_yaml, Loader=yaml.Loader)` and `yaml.dump(your_dataclass_instance)` helpers. It should be basically as flexible as pickle, bigger file sizes but still human-readable + editable.
